#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

chown -R sail:sail /var/www/html/storage
chmod -R 775 /var/www/html/storage

# Crea el enlace simbólico si no existe (útil para logs/caché o si decides usarlo para algo más)
if [ ! -L /var/www/html/public/storage ]; then
    php artisan storage:link
fi

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    # Iniciar Supervisor para gestionar PHP-FPM
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
